name: openapi_doc
description: OpenAPI doc generator.
version: 0.1.2
homepage: https://github.com/curvednebula/docbaker-cli

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  pdf: ^3.7.3
  intl: ^0.17.0
  args: ^2.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
